sudo: true
services:
  - docker

before_install:
  - docker pull mongo:3.4.8
  - docker pull docker.elastic.co/elasticsearch/elasticsearch:6.2.4
  - docker pull postgres:9.6.5
  - docker pull quay.io/whisk/fastboot-mysql:5.7.19

language: scala

scala:
  - 2.12.8
  - 2.11.12

jdk:
  - oraclejdk8

script:
  - sbt tests/test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete